# Generated by Django 4.2.3 on 2023-07-26 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peterdjang', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
