# Generated by Django 4.2.3 on 2023-07-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peterdjang', '0004_people_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='city',
            field=models.CharField(default='nairobi', max_length=30),
        ),
        migrations.AddField(
            model_name='people',
            name='country',
            field=models.CharField(default='kenya', max_length=30),
        ),
        migrations.AlterField(
            model_name='people',
            name='phone',
            field=models.IntegerField(default=1),
        ),
    ]
